FROM node:16-alpine as node_modules_cache
WORKDIR /cache/
# if native modules are needed: make gcc g++ python3
RUN apk add --no-cache git   
COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install

FROM node:16-alpine
WORKDIR /app
RUN apk add --no-cache git
COPY --from=node_modules_cache /cache/ .
COPY . .
# DevTools/Debugger
EXPOSE 9229

CMD ["./node_modules/.bin/concurrently", "'./node_modules/.bin/ts-node-dev", "--inspect=0.0.0.0:9229", "--poll", "--respawn", "--ignore-watch", "node_modules", "--transpile-only", "src/index.ts'", "'./node_modules/.bin/nodemon", "-L", "--watch", "./src/locales", "-e json", "--", "./node_modules/ts-json-as-const", "src/locales/en-US.json'"]
