services:
  website:
    image: nginx:latest
    container_name: website
    restart: always
    ports:
      - "3000:80"
    env_file:
      - .env
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - member-counter-dev

  mongo:
    image: mongo:7
    container_name: MongoDB
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh --quiet | grep 1
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 20s
    ports:
      - 27017:27017
    volumes:
      - ./storage/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
    networks:
      - member-counter-dev

  setup-mongo-rs:
    image: mongo:7
    container_name: Setup-MongoDB-ReplicaSet
    command: 'mongosh mongodb://mongo:27017/memberCounter --eval=''rs.initiate({ _id: "rs0", members: [{_id: 0, host:"mongo:27017"}] }).ok'' --quiet | grep 1'
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    restart: "no"
    networks:
      - member-counter-dev

  mongoex:
    image: mongo-express
    container_name: MongoEX
    networks:
      - member-counter-dev
    ports:
      - "3001:8081"
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    restart: unless-stopped

  redis:
    image: redis
    command: redis-server
    container_name: Redis
    restart: unless-stopped
    networks:
      - member-counter-dev
    ports:
      - "6379:6379"

  redis-insight:
    container_name: Redis-Insight
    image: redis/redisinsight:latest
    networks:
      - member-counter-dev
    depends_on:
      - redis
    healthcheck:
      test: wget -qO- http://redis-insight:5540/api/health | grep up
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 20s
    ports:
      - "3002:5540"
    restart: unless-stopped

  setup-redis-insight:
    container_name: Setup-Redis-Insight
    image: curlimages/curl
    networks:
      - member-counter-dev
    depends_on:
      redis-insight:
        condition: service_healthy
        restart: true
    command: |
      curl
        --connect-timeout 5 --max-time 10 --retry 10 --retry-delay 2 --retry-max-time 40 --retry-connrefused
        --location --request POST 'http://redis-insight:5540/api/databases/'
        --header 'Content-Type: application/json'
        --data-raw '{
            "name": "Local",
            "host": "redis",
            "port": 6379,
            "compressor": "NONE",
            "db": 0,
            "timeout": 30000
        }'

configs:
  nginx.conf:
    content: |
      worker_processes 1;
      events { worker_connections 1024; }

      http {
          upstream backend-upstream {
            server host.docker.internal:8080;
          }

          upstream frontend-upstream {
            server host.docker.internal:5173;
          }

          server {
              listen 80;
              server_name _;

              location /api {
                  rewrite ^/api/(.*)$$ /$$1 break;

                  proxy_pass http://backend-upstream;
                  proxy_http_version 1.1;
                  
                  proxy_set_header Host $$http_host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  proxy_set_header X-Forwarded-Host $$http_host;
                  proxy_set_header X-Forwarded-Port $$server_port;
                  proxy_set_header Upgrade $$http_upgrade;
                  proxy_set_header Connection "upgrade";
              }

              location / {
                  proxy_pass http://frontend-upstream;
                  proxy_http_version 1.1;

                  proxy_set_header Upgrade $$http_upgrade;
                  proxy_set_header Connection "upgrade";
              }
          }
      }

networks:
  member-counter-dev:
