version: "3.7"

services:
  member-counter-bot-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: member-counter-bot:latest
    container_name: Member-Counter-App-Dev
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - member-counter-bot-mongodb
      - member-counter-bot-redis
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    networks:
      - default

  member-counter-bot-mongodb:
    image: mongo:4.4.6
    container_name: Member-Counter-DB
    restart: always
    volumes:
      - ./storage/db:/data/db
      - ./storage/configdb:/data/configdb
    logging:
      driver: "none"
    networks:
      - default
    ports:
      - "27017:27017"

  member-counter-bot-redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: Member-Counter-Redis
    logging:
      driver: "none"
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"

  member-counter-bot-mongoex:
    image: mongo-express
    container_name: Member-Counter-MongoEX
    logging:
      driver: "none"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=monokai
      - ME_CONFIG_MONGODB_SERVER=member-counter-bot-mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    depends_on:
      - member-counter-bot-mongodb
    restart: unless-stopped

networks:
  default:
